language: python
python:
        - "3.6"
        - "3.8"
install:
        - pip install -r requirements.txt
        - pip install aiohttp[speedups] nest_asyncio
        - pip install nose
script:
        python setup.py test
